In [5]:
#import library
import pandas as pd
import numpy as np

In [7]:
#load data
df = pd.read_csv("parkinsons.data")
df

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0    phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1    phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2    phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3    phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4    phon_R01_S01_5      116.014       141.781       110.655         0.01284   
..              ...          ...           ...           ...             ...   
190  phon_R01_S50_2      174.188       230.978        94.261         0.00459   
191  phon_R01_S50_3      209.516       253.017        89.488         0.00564   
192  phon_R01_S50_4      174.688       240.005        74.287         0.01360   
193  phon_R01_S50_5      198.764       396.961        74.904         0.00740   
194  phon_R01_S50_6      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0             0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1             0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2             0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3             0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4             0.00011   0.00655   0.00908     0.01966       0.06425  ...   
..                ...       ...       ...         ...           ...  ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087  ...   
191           0.00003   0.00331   0.00292     0.00994       0.02751  ...   
192           0.00008   0.00624   0.00564     0.01873       0.02308  ...   
193           0.00004   0.00370   0.00390     0.01109       0.02296  ...   
194           0.00003   0.00295   0.00317     0.00885       0.01884  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0        0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1        0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2        0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3        0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4        0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   
..           ...      ...     ...     ...       ...       ...       ...   
190      0.07008  0.02764  19.517       0  0.448439  0.657899 -6.538586   
191      0.04812  0.01810  19.147       0  0.431674  0.683244 -6.195325   
192      0.03804  0.10715  17.883       0  0.407567  0.655683 -6.787197   
193      0.03794  0.07223  19.020       0  0.451221  0.643956 -6.744577   
194      0.03078  0.04398  21.209       0  0.462803  0.664357 -5.724056   

      spread2        D2       PPE  
0    0.266482  2.301442  0.284654  
1    0.335590  2.486855  0.368674  
2    0.311173  2.342259  0.332634  
3    0.334147  2.405554  0.368975  
4    0.234513  2.332180  0.410335  
..        ...       ...       ...  
190  0.121952  2.657476  0.133050  
191  0.129303  2.784312  0.168895  
192  0.158453  2.679772  0.131728  
193  0.207454  2.138608  0.123306  
194  0.190667  2.555477  0.148569  

[195 rows x 24 columns]

In [8]:
df.head(23)

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0   phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1   phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2   phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3   phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4   phon_R01_S01_5      116.014       141.781       110.655         0.01284   
5   phon_R01_S01_6      120.552       131.162       113.787         0.00968   
6   phon_R01_S02_1      120.267       137.244       114.820         0.00333   
7   phon_R01_S02_2      107.332       113.840       104.315         0.00290   
8   phon_R01_S02_3       95.730       132.068        91.754         0.00551   
9   phon_R01_S02_4       95.056       120.103        91.226         0.00532   
10  phon_R01_S02_5       88.333       112.240        84.072         0.00505   
11  phon_R01_S02_6       91.904       115.871        86.292         0.00540   
12  phon_R01_S04_1      136.926       159.866       131.276         0.00293   
13  phon_R01_S04_2      139.173       179.139        76.556         0.00390   
14  phon_R01_S04_3      152.845       163.305        75.836         0.00294   
15  phon_R01_S04_4      142.167       217.455        83.159         0.00369   
16  phon_R01_S04_5      144.188       349.259        82.764         0.00544   
17  phon_R01_S04_6      168.778       232.181        75.603         0.00718   
18  phon_R01_S05_1      153.046       175.829        68.623         0.00742   
19  phon_R01_S05_2      156.405       189.398       142.822         0.00768   
20  phon_R01_S05_3      153.848       165.738        65.782         0.00840   
21  phon_R01_S05_4      153.880       172.860        78.128         0.00480   
22  phon_R01_S05_5      167.930       193.221        79.068         0.00442   

    MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0            0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1            0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2            0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3            0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4            0.00011   0.00655   0.00908     0.01966       0.06425  ...   
5            0.00008   0.00463   0.00750     0.01388       0.04701  ...   
6            0.00003   0.00155   0.00202     0.00466       0.01608  ...   
7            0.00003   0.00144   0.00182     0.00431       0.01567  ...   
8            0.00006   0.00293   0.00332     0.00880       0.02093  ...   
9            0.00006   0.00268   0.00332     0.00803       0.02838  ...   
10           0.00006   0.00254   0.00330     0.00763       0.02143  ...   
11           0.00006   0.00281   0.00336     0.00844       0.02752  ...   
12           0.00002   0.00118   0.00153     0.00355       0.01259  ...   
13           0.00003   0.00165   0.00208     0.00496       0.01642  ...   
14           0.00002   0.00121   0.00149     0.00364       0.01828  ...   
15           0.00003   0.00157   0.00203     0.00471       0.01503  ...   
16           0.00004   0.00211   0.00292     0.00632       0.02047  ...   
17           0.00004   0.00284   0.00387     0.00853       0.03327  ...   
18           0.00005   0.00364   0.00432     0.01092       0.05517  ...   
19           0.00005   0.00372   0.00399     0.01116       0.03995  ...   
20           0.00005   0.00428   0.00450     0.01285       0.03810  ...   
21           0.00003   0.00232   0.00267     0.00696       0.04137  ...   
22           0.00003   0.00220   0.00247     0.00661       0.04351  ...   

    Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0       0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1       0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2       0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3       0.08771  0.0

In [11]:
feature = df.loc[:,df.columns != 'status'].values[:,1:]
feature

array([[119.992, 157.302, 74.997, ..., 0.266482, 2.301442, 0.284654],
       [122.4, 148.65, 113.819, ..., 0.33559, 2.486855, 0.368674],
       [116.682, 131.111, 111.555, ..., 0.311173, 2.342259, 0.332634],
       ...,
       [174.688, 240.005, 74.287, ..., 0.158453, 2.679772, 0.131728],
       [198.764, 396.961, 74.904, ..., 0.207454, 2.138608, 0.123306],
       [214.289, 260.277, 77.973, ..., 0.190667, 2.555477, 0.148569]],
      dtype=object)

In [12]:
labels = df.loc[:,'status'].values
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [13]:
labels[labels==1].shape[0]

147

In [14]:
labels[labels==0].shape[0]

48

In [16]:
#Why only use minMaxScaler in feature beacuse the features have different range of values
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler((-1,1))
x = scaler.fit_transform(feature)
y = labels

In [17]:
x

array([[-0.63138346, -0.77481654, -0.89037042, ...,  0.17153026,
        -0.21867743, -0.0053808 ],
       [-0.6033463 , -0.81013911, -0.4433544 , ...,  0.48267409,
        -0.05370956,  0.34265204],
       [-0.66992292, -0.88174367, -0.46942324, ...,  0.37274182,
        -0.18236124,  0.19336492],
       ...,
       [ 0.00546073, -0.43717403, -0.89854572, ..., -0.31484696,
         0.11793486, -0.63884033],
       [ 0.28578581,  0.20361309, -0.89144127, ..., -0.09423055,
        -0.36355605, -0.67372646],
       [ 0.46654868, -0.35441175, -0.85610326, ..., -0.16981039,
         0.00734563, -0.5690805 ]])

In [18]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [21]:
#split it into train ans test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [22]:
x_train

array([[-0.64228163, -0.9058228 , -0.75452232, ...,  0.11942533,
        -0.02749361, -0.22262172],
       [-0.56561023, -0.84109332, -0.41425726, ...,  0.14451205,
         0.39490041,  0.35212539],
       [-0.03700254, -0.5665595 , -0.88456711, ..., -0.00947956,
         0.0377967 , -0.57391038],
       ...,
       [-0.30210977, -0.74343366, -0.11542137, ..., -0.63276672,
        -0.18051327, -0.41200593],
       [-0.30361176, -0.78020556, -0.19899363, ...,  0.05624028,
         0.26504047, -0.38615408],
       [-0.40745872,  0.97769681, -0.99215862, ...,  0.19025526,
         0.12785092,  0.65787817]])

In [24]:
#train the model
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(x_train,y_train)
y_pred = xgb.predict(x_test)

C:\Users\Payal\AppData\Local\Programs\Python\Python39\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[20:36:26] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9538461538461539

In [27]:
#percentage
round(accuracy_score(y_test,y_pred),4)*100

95.38